import pycountry
from wtforms import SelectField


class CountrySelectField(SelectField):
    """Custom SelectField definition for Country"""

    def __init__(self, *args, **kwargs):
        super(CountrySelectField, self).__init__(*args, **kwargs)
        self.choices = [(country.alpha_2, country.name) for country in pycountry.countries]


class DepartmentSelectField(SelectField):
    """Custom SelectField definition for Department"""

    def __init__(self, *args, **kwargs):
        super(DepartmentSelectField, self).__init__(*args, **kwargs)
        self.choices = [('ACC', 'Accounting'),
                        ('ASE', 'Aerospace Engineering'),
                        ('AS', 'Aerospace Studies - AFROTC'),
                        ('AAS', 'African American Studies'),
                        ('AELC', 'Ag Educ,Leadership & Comm'),
                        ('ABE', 'Ag. and Bio. Engineering'),
                        ('AEC', 'Agricultural Economics'),
                        ('AIS', 'Agricultural Info Sci & Ed'),
                        ('AGN', 'Agronomy'),
                        ('ADS', 'Animal Science & Dairy Science'),
                        ('AN', 'Anthropology'),
                        ('ALHP', 'Appalachian Ldshp Honors Prog'),
                        ('AR', 'Archaeology'),
                        ('ARC', 'Architecture'),
                        ('ART', 'Art'),
                        ('BAT', 'BAT Transfer Technical Course'),
                        ('BCH', 'Biochemistry'),
                        ('BIO', 'Biological Sciences'),
                        ('BCS', 'Building Construction Science'),
                        ('BUS', 'Business Adminstration'),
                        ('BIS', 'Business Information Systems'),
                        ('BL', 'Business Law'),
                        ('BQA', 'Business Quantitive Analysis'),
                        ('TKB', 'Business Technology'),
                        ('BTE', 'Business Technology Education'),
                        ('CHE', 'Chemical Engineering'),
                        ('CH', 'Chemistry'),
                        ('FLC', 'Chinese'),
                        ('CE', 'Civil Engineering'),
                        ('CFR', 'College of Forest Resources'),
                        ('CO', 'Communication'),
                        ('CCL', 'Community College Leadership'),
                        ('CMB', 'Computational Biology'),
                        ('CME', 'Computational Engineering'),
                        ('CPE', 'Computer Engineering'),
                        ('CSE', 'Computer Science & Engineering'),
                        ('CP', 'Cooperative Education Program'),
                        ('COR', 'Corrections'),
                        ('COE', 'Counselor Education'),
                        ('CRM', 'Criminology'),
                        ('CA', 'Culinary Arts'),
                        ('DSS', 'Disability Support Services'),
                        ('EC', 'Economics'),
                        ('EDC', 'Education Core Curriculum'),
                        ('EDTB', 'Education Student Block'),
                        ('EDST', 'Education Student Teaching'),
                        ('EDF', 'Educational Foundations'),
                        ('EDA', 'Educational Leadership (EDA)'),
                        ('EDL', 'Educational Leadership (EDL)'),
                        ('EPY', 'Educational Psychology'),
                        ('ECE', 'Electrical & Computer Engineer'),
                        ('EE', 'Electrical Engineering'),
                        ('EDE', 'Elementary Education'),
                        ('ENE', 'Engineering Education'),
                        ('EG', 'Engineering Graphics'),
                        ('EM', 'Engineering Mechanics'),
                        ('EN', 'English'),
                        ('ESL', 'English as Second Language'),
                        ('EAP', 'English for Academic Purposes'),
                        ('EPP', 'Entomology & Plant Pathology'),
                        ('ENS', 'Environmental Science'),
                        ('EP', 'Exercise Physiology'),
                        ('EXL', 'Experiental Learning'),
                        ('FDM', 'Fashion Design & Merchandising'),
                        ('FIN', 'Finance'),
                        ('FYE', 'First Year Experience'),
                        ('FNH', 'Food, Nutrition & Health Promo'),
                        ('FL', 'Foreign Languages'),
                        ('FP', 'Forest Products'),
                        ('FO', 'Forestry'),
                        ('FLF', 'French'),
                        ('GLA', 'Gen Liberal Arts'),
                        ('GS', 'Gender Studies'),
                        ('GA', 'General Agriculture'),
                        ('GB', 'General Business'),
                        ('GE', 'General Engineering'),
                        ('GNS', 'Genetics'),
                        ('GR', 'Geography'),
                        ('GG', 'Geology'),
                        ('FLG', 'German'),
                        ('GRD', 'Graduate Studies'),
                        ('FLH', 'Greek'),
                        ('HCA', 'Healthcare Administration'),
                        ('HED', 'Higher Education'),
                        ('HI', 'History'),
                        ('HON', 'Honors College'),
                        ('HDFS', 'Human Development & Family Sci'),
                        ('HS', 'Human Sciences'),
                        ('IE', 'Industrial Engineering'),
                        ('TKI', 'Industrial Technology'),
                        ('INDT', 'Industrial Technology'),
                        ('INS', 'Insurance & Risk Management'),
                        ('IDS', 'Interdisciplinary Studies'),
                        ('ID', 'Interior Design'),
                        ('IB', 'International Business'),
                        ('ISE', 'International Student Exchange'),
                        ('FLI', 'Italian'),
                        ('FLJ', 'Japanese'),
                        ('KI', 'Kinesiology'),
                        ('LA', 'Landscape Architecture'),
                        ('FLL', 'Latin'),
                        ('LSK', 'Learning Skills'),
                        ('LIB', 'Library'),
                        ('MGT', 'Management'),
                        ('DTM', 'Manufacturing'),
                        ('MKT', 'Marketing'),
                        ('MA', 'Mathematics'),
                        ('ME', 'Mechanical Engineering'),
                        ('MIC', 'Microbiology'),
                        ('MEC', 'Middle Eastern Culture'),
                        ('MS', 'Military Science - Army ROTC'),
                        ('MU', 'Music'),
                        ('MUE', 'Music Education'),
                        ('MUA', 'Music, Applied'),
                        ('NSE', 'National Student Exchange'),
                        ('NREC', 'Natural Resource & Envir Cons'),
                        ('PTE', 'Petroleum Engineering'),
                        ('PHI', 'Philosophy'),
                        ('PE', 'Physical Education'),
                        ('PAS', 'Physician Assistant Studies'),
                        ('PH', 'Physics'),
                        ('PHY', 'Physiology'),
                        ('PSS', 'Plant and Soil Sciences'),
                        ('PS', 'Political Science'),
                        ('PO', 'Poultry Science'),
                        ('PSY', 'Psychology'),
                        ('PPA', 'Public Policy & Administration'),
                        ('RDG', 'Readings in Education'),
                        ('REF', 'Real Estate Finance'),
                        ('REL', 'Religion'),
                        ('FLR', 'Russian'),
                        ('EDS', 'Secondary Education'),
                        ('SL', 'Service Learning'),
                        ('SW', 'Social Work'),
                        ('SO', 'Sociology'),
                        ('FLS', 'Spanish'),
                        ('EDX', 'Special Education'),
                        ('SS', 'Sport Studies'),
                        ('ST', 'Statistics'),
                        ('SLCE', 'Student Ldshp Comm Engagement'),
                        ('SBP', 'Sustainable Bioproducts'),
                        ('TECH', 'Technology'),
                        ('DTF', 'Technology Foundations'),
                        ('TKT', 'Technology Teacher Education'),
                        ('TR', 'Transportation'),
                        ('UHP', 'University Honors Program'),
                        ('VTP', 'Veterans Transition Program'),
                        ('CVM', 'Veterinary Medicine'),
                        ('VS', 'Veterinary Science'),
                        ('WFA', 'Wildlife,Fisheries, & Aquaculture'),
                        ('WS', "Women's Studies")]
